name: Linux
on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        ubuntu_version: [ubuntu-18.04, ubuntu-20.04]
        compiler: [clang, gcc]
    runs-on: ${{ matrix.ubuntu_version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build
        env:
          CC: ${{ matrix.compiler }}
        run: |
          sudo apt update
          sudo apt install check
          ./autogen.sh
          ./configure --with-check
          make -j
          make check
          make dist-xz
          sudo make install
